version: 2.1

jobs:
  publish:
    docker:
      - image: cimg/node:12.20.1
    steps:
      - checkout
      - run: npm run build
      - run: npm version patch

workflows:
  version: 2
  build:
    jobs:
      - publish:
          context: npm
          filters:
            branches:
              only:
                - main
